### ISSUE TITLE
[FEATURE] CLI: no-color option

### ISSUE THREAD

**Issue by jakobjung10** [HDLUtils/hdlregression#13]
Is it possible to add a no-color-option to the CLI? (
This would make parsing the console-output of HDLRegression easier.
Currently, the output has to be filtered manually in order to remove all the special ANSI-chars.

**Comment by HDLUtils** [comment]
Good suggestion, I will add it soon.

Br.

**Comment by HDLUtils** [comment]
Added to version 0.43, use `--noColor` argument to disable terminal output coloring.

**Comment by jakobjung10** [comment]
Thank you!
