### ISSUE TITLE
Warnings from Python 3.11 during install

### ISSUE THREAD

**Issue by dbemlogic** [HDLUtils/hdlregression#16]
I'm getting the following warnings during installation with Python 3.11.

$ python setup.py build

"...\Python\Python311\Lib\site-packages\setuptools\dist.py:160: UserWarning: newlines not allowed and will break in the future
  warnings.warn("newlines not allowed and will break in the future")"

$ python setup.py develop

"...Python\Python311\Lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools."

"...Python\Python311\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools."

It seems from the two last warnings like the installation method for HDLregression is outdated.

**Comment by HDLUtils** [comment]
Changed to PIP install method
