### ISSUE TITLE
No sim option becomes sticky.

### ISSUE THREAD

**Issue by drowzie** [HDLUtils/hdlregression#19]
Providing the no sim option(-ns) to hdlreg becomes sticky, where it will permanently skip simulation if you attempt to rerun without the -ns option. A recompilation (-c option) is necessary to start simulation again.

I assume this is related to settings being saved from each compilation? Suggestion is perhaps to have runtime settings that will not be saved between runs.

**Comment by HDLUtils** [comment]
Hi, thanks for reporting this issue.
I will have to investigate a bit. The settings are reset after each regression run and only default settings are stored in the database, except when entering GUI mode with Modelsim. Could you explain when you see this issue?

**Comment by drowzie** [comment]
Hopefully trivial to reproduce.
Whenever i run the script with hdlregression eg. `main.py` it will run normally and compile related files, and run testbenches that are provided.

I apply -ns as an arugment and the usual "Skipping Simulations" text isprovided. After this the Skipping Simulation will always be printed and no simulation is run.

Providing -c for recompilation will "reset" and it will run simulation again.
