### ISSUE TITLE
Argument parsing creates conflict with HDLRegression argument parsing

### ISSUE THREAD

**Issue by drowzie** [HDLUtils/hdlregression#2]
The HDLRegressions argument parser will run on top of the argument parser in my main script creating the HDLRegression Class. I assume it is because of the function `self.args = arg_parser_reader()` always being called.

I created my own argument parser as such and it will create a conflict on certain HDLRegression arguments. Some are required inside my own argp function if i want to support Hdlregression arguments such as gui -g. This creates the necesity to write arguments that are already in arg_parser_reader.
```
def argp():
	parser = argparse.ArgumentParser(
			prog = "Simulation build script",
			description = "To simulate specific or all testbenches for Modelsim",
		)

	parser.add_argument('--tb_path')
	parser.add_argument('-v', '-verbose', action='store_true')
	parser.add_argument('-g', '-gui', action='store_true')
	args = parser.parse_args()
	return args
	
if __name__ == "__main__":
	args = argp()
	hr = HDLRegression()
```

**Comment by HDLUtils** [comment]
Hi,
The next version will accept a argparse object to be passed to the init method, i.e. HDLRegression(arg_parser=my_custom_parser), with a method to read out the parsed arguments hr.get_args().

```
def argp():
	parser = argparse.ArgumentParser(
			prog = "Simulation build script",
			description = "To simulate specific or all testbenches for Modelsim",
		)
	parser.add_argument('--tb_path')
	return parser
	
if __name__ == "__main__":
	custom_parser = argp()
	
	hr = HDLRegression(arg_parser=custom_parser)
	parsed_args = hr.get_args()
	...
	hr.add_files(.....)
	....
	# do stuff with parsed args
	....
	hr.start()
```

**Comment by HDLUtils** [comment]
Solution added to version 0.32
