### ISSUE TITLE
Simulator not available 

### ISSUE THREAD

**Issue by fpgaDave** [HDLUtils/hdlregression#21]
I am evaluating whether to use HDLRegression. I'm a python noob so it's likely that is my issue.
Perhaps there is a help resource somewhere?
I'm following the hdlregression.pdf guide

When running assertion_test.py I get many messages:
Simulator  not available. Autodetecting
the resultant logs look like the simulator cannot be found.

I have tried adding hr.set_simulator as below:
hr = HDLRegression()
hr.set_simulator(simulator="MODELSIM", path='C:/Microchip/Libero_SoC_v2024.1/ModelSimPro/win32acoem/modelsim.exe')

and get this error:
Simulator change require new databases - delete ./hdlregression folder and rerun test suite.

deleting the folder did not help, swapping the order did not help. Neither did removing the .exe from the path.
I also tried adding modelsim env variables to no avail.

**Comment by HDLUtils** [comment]
Hi Dave.
Which version of HDLRegression are you running? From version 0.5 the tool will try to autodetect which simulator to run, selecting in the following order:
1. Modelsim
2. NVC
3. GHDL
If you have several Modelsim versions installed it will select the one on top of your environmental variables.

Can you try with:
1. delete to hdlregression folder, i.e. start with a clean run.
2. remove the `hr.set_simulator(....)` call from your Python script.
3. modify object creation to `hr = HDLRegression(simulator="MODELSIM")`
4. run the regression script without any arguments

If this does not work, try to also add the Microchip Modelsim folder (`C:/Microchip/Libero_SoC_v2024.1/ModelSimPro/win32acoem/`) to the top of your environment variables list.

Br

**Comment by HDLUtils** [comment]
Fixed in version 0.51
