### ISSUE TITLE
set_code_coverage issue

### ISSUE THREAD

**Issue by rsek1498** [HDLUtils/hdlregression#22]
Hi,
I've set the following option:
hr.set_code_coverage("bcsf", "code_coverage.ucdb")

And I've got the following message:
    Invalid coverge settings in: bcsf

I've try to set the simulator but the result is the same (hr.start(simulator="MODELSIM"))

I didn't have this message in the previous version (0.50).
Best regards

**Comment by HDLUtils** [comment]
Hi, could you paste the full transcript and paste it here? I.e., run with full verbosity "-v"

**Comment by rsek1498** [comment]
Thank you for your quick response

For information:
========================================================================================================================
  HDLRegression version 0.51.1
  See /doc/hdlregression.pdf for documentation.
========================================================================================================================


Invalid coverge settings in: bcsf
Scanning files...
Building test suite structure...
Simulator: MODELSIM

...

**Comment by HDLUtils** [comment]
Issue corrected in v0.51.2

**Comment by rsek1498** [comment]
There are no more error messages now!
👍
