### ISSUE TITLE
back-up not created each time script is run

### ISSUE THREAD

**Issue by jonathanbxxx** [HDLUtils/hdlregression#27]
According to the documentation the test folder is back-up each time the script is run with a data-and-time stamp. I am not seeing this each time the script is run the tests are appended to the reports in the test folder.

**Comment by jonathanbxxx** [comment]
Closing issue, I misunderstood how this works. I think I understand it now, the backup is created when the test is re-run following a successful run.

**Comment by UVVM** [comment]
Hi, great to hear that you figured out.

Br
