### ISSUE TITLE
Suggestion: Allow more control and flexibility with the start() command.

### ISSUE THREAD

**Issue by drowzie** [HDLUtils/hdlregression#4]
I have a suggestions that could be useful in some cases for more complex control of HDLReg.

To allow manual control over running compilation and simulation. In some cases i have seen that i want to only run compilation to verify that the code is in a working standard, but i do not want to run the testbenches. Thus a suggestion is to expand start() function to be able to run things separately. E.g run_compilation, run_simulation.

With the previous addition it could be helpful for certain cases where one might want to alter the files post compilation but pre-simulation. E.g modelsim.ini

**Comment by HDLUtils** [comment]
Thanks, We have several requests for this functionality, so thius will be implemented soon.

**Comment by HDLUtils** [comment]
Hi @drowzie,
The 0.40 release has added CLI arguments `'-ns'` and `'--no_sim'` to run without simulation, i.e. only compilation.
